# Generated by Django 4.2.27 on 2026-02-02 16:39

from django.db import migrations, models
import jagalchi_ai.ai_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeResource',
            fields=[
                ('resource_id', models.CharField(default=jagalchi_ai.ai_core.models.generate_resource_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('node_id', models.CharField(help_text='관련 노드 ID', max_length=100)),
                ('title', models.CharField(help_text='자료 제목', max_length=255)),
                ('url', models.URLField(help_text='자료 URL', max_length=500)),
                ('source', models.CharField(choices=[('web', 'Web'), ('internal', 'Internal'), ('generated', 'Generated')], default='web', help_text='출처 (web/internal/generated)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='자료 설명', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_node_resource',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node_id'], name='ai_node_res_node_id_e51c29_idx')],
            },
        ),
        migrations.CreateModel(
            name='InitData',
            fields=[
                ('init_data_id', models.CharField(default=jagalchi_ai.ai_core.models.generate_init_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('roadmap_id', models.CharField(help_text='관련 로드맵 ID', max_length=100)),
                ('content', models.TextField(help_text='데이터 내용')),
                ('data_type', models.CharField(choices=[('file', 'File'), ('text', 'Text')], default='text', help_text='데이터 타입 (file/text)', max_length=10)),
                ('filename', models.CharField(blank=True, help_text='파일명 (파일인 경우)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_init_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['roadmap_id'], name='ai_init_dat_roadmap_571382_idx')],
            },
        ),
    ]
